# Site settings
title: Travel Agency Page
description: Travel Agency Make-My-Visa

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://make-my-visa.com.ua" # the base hostname & protocol for your site


# Build settings
encoding: utf-8
markdown: kramdown
permalink: /:title.html

include: [.htaccess]

# Social contacts
facebook: https://www.facebook.com/pages/MAKE-MY-VISA/440928226067863
vk: https://vk.com/makemyvisa
email: makemyvisa2015@gmail.com
gplus: https://plus.google.com/u/0/114703891393318435936

gems:
  - jekyll-sitemap